	<p align="center" style="margin-top:50px">
		<a href="http://www.facebook.com/group.php?gid=2224131220&ref=ts" target="_blank"><img src="img/facebook.gif" border="0"/></a>
    	<a href="http://twitter.com/hedrickchris" target="_blank"><img src="img/twitter.gif" border="0" /></a></p>

	<hr />

	<p align="center">
		<a href="index.php">Home</a> | <a href="http://peacecorps.gov" target="_blank">PeaceCorps.gov</a> | <a class="popup" href="contact_us.html">Contact Us</a> | <a class="popup" href="disclaimer.html">Disclaimer</a></p>
    
	<p align="center">
		<!-- AddThis Button BEGIN -->
		<a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=250&amp;pub=xa-4a92696a44b970fd">
        	<img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/>
        </a>
		<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js?pub=xa-4a92696a44b970fd"></script>
		<!-- AddThis Button END --></p>

	</div><!--END col_right-->
    <div id="footer">
    	<img id="logo_footer" src="img/photo_strip.jpg" />
    </div><!--END footer-->
</div><!--END container-->

<script type="text/javascript">
	var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
	document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
	try {
		var pageTracker = _gat._getTracker("UA-12649260-1");
		pageTracker._trackPageview();
	} catch(err) {}
</script>