<div id="google_search">
<!-- Google search -->
<form method="get" action="http://www.google.com/search">
	<input type="hidden" name="ie" value="UTF-8" />
	<input type="hidden" name="oe" value="UTF-8" />
	<input type="hidden" name="domains" value="http://pcsenegal.org" />
	<input type="hidden" name="sitesearch" value="http://pcsenegal.org" checked />

		<input type="text" name="q" maxlength="200" value="" />
		<input type="submit" name="btnG" value="Google Search" />

</form>
<!--END Search Google -->
</div>