<div id="main_container" class="ddsmoothmenu-v">
  <ul id="nav" class="MenuBarVertical">
    <li><a href="index.php?page=home.html">Welcome</a></li>
    <li><a href="index.php?page=blog/index.html">Director's Blog</a></li>
    <li><a href="index.php?page=who_we_are/index.html">Who We Are</a>
    	<ul>
    		<li><a href="index.php?page=who_we_are/volunteers.html">Volunteers</a></li>
    		<li><a href="index.php?page=pcresponse/index.html">Peace Corps Response</a></li>
    		<li><a href="index.php?page=who_we_are/staff/index.html">Staff</a>
    			<ul>
    				<li><a href="index.php?page=who_we_are/staff/index.html">APCDs</a></li>
    				<li><a href="index.php?page=who_we_are/staff/support.html">Programming & Support</a></li>
    				<!--<li><a href="index.php?page=who_we_are/staff/medical.html">Medical</a></li>
    				<li><a href="index.php?page=who_we_are/staff/finance.html">Finance</a></li>
    				<li><a href="index.php?page=who_we_are/staff/it.html">IT</a></li>
    				<li><a href="index.php?page=who_we_are/staff/motor_pool.html">Motor Pool</a></li>-->
    			</ul></li>
    		<li><a href="index.php?page=contact_us.html">Contact Us</a></li>
    	</ul></li>
    <li><a href="index.php?page=what_we_do.html">What We Do</a>
      <ul>
      	<li><a href="index.php?page=regions/index.html">Where We Work</a>
        	<ul>
        		<li><a href="index.php?page=regions/dakar/index.html">Dakar</a></li>
        		<li><a href="index.php?page=regions/fatick/index.html">Fatick</a></li>
        		<li><a href="index.php?page=regions/kaffrine/index.html">Kaffrine</a></li>
        		<li><a href="index.php?page=regions/kaolack/index.html">Kaolack</a></li>
        		<li><a href="index.php?page=regions/kedougou/index.html">Kedougou</a></li>
        		<li><a href="index.php?page=regions/kolda/index.html">Kolda</a></li>
        		<li><a href="index.php?page=regions/louga/index.html">Louga</a></li>
        		<li><a href="index.php?page=regions/north/index.html">Northern Senegal</a></li>
        		<li><a href="index.php?page=regions/tamba/index.html">Tambacounda</a></li>
        		<li><a href="index.php?page=regions/thies/index.html">Thies</a></li>
            </ul></li>
      	<li><a href="index.php?page=sectors/index.html">Sectors</a>
        	<ul>
        		<li><a href="index.php?page=sectors/agfo/index.html">Agroforestry</a></li>
        		<li><a href="index.php?page=sectors/ecot/index.html">Ecotourism</a></li>
        		<li><a href="index.php?page=sectors/ee/index.html">Environmental Education</a></li>
        		<li><a href="index.php?page=sectors/he/index.html">Health</a>
        			<ul>
        				<li><a href="http://pcsenegal.org/index.php?page=malaria/index.html">PC Senegal & Malaria</a></li>
     