<div id="main_container" class="ddsmoothmenu-v">
  <ul id="nav" class="MenuBarVertical">
    <li><a href="index.php?page=home.html">Welcome</a></li>
    <li><a href="index.php?page=blog/index.html">Director's Blog</a></li>
    <li><a href="index.php?page=who_we_are/index.html">Who We Are</a>
    	<ul>
    		<li><a href="index.php?page=who_we_are/volunteers.html">Volunteers</a></li>
    		<li><a href="index.php?page=pcresponse/index.html">Peace Corps Response</a></li>
    		<li><a href="index.php?page=who_we_are/staff/index.html">Staff</a>
    			<ul>
    				<li><a href="index.php?page=who_we_are/staff/index.html">APCDs</a></li>
    				<li><a href="index.php?page=who_we_are/staff/support.html">Programming & Support</a></li>
    				<!--<li><a href="index.php?page=who_we_are/staff/medical.html">Medical</a></li>
    				<li><a href="index.php?page=who_we_are/staff/finance.html">Finance</a></li>
    				<li><a href="index.php?page=who_we_are/staff/it.html">IT</a></li>
    				<li><a href="index.php?page=who_we_are/staff/motor_pool.html">Motor Pool</a></li>-->
    			</ul></li>
    		<li><a href="index.php?page=contact_us.html">Contact Us</a></li>
    	</ul></li>
    <li><a href="index.php?page=what_we_do.html">What We Do</a>
      <ul>
      	<li><a href="index.php?page=regions/index.html">Where We Work</a>
        	<ul>
        		<li><a href="index.php?page=regions/dakar/index.html">Dakar</a></li>
        		<li><a href="index.php?page=regions/fatick/index.html">Fatick</a></li>
        		<li><a href="index.php?page=regions/kaffrine/index.html">Kaffrine</a></li>
        		<li><a href="index.php?page=regions/kaolack/index.html">Kaolack</a></li>
        		<li><a href="index.php?page=regions/kedougou/index.html">Kedougou</a></li>
        		<li><a href="index.php?page=regions/kolda/index.html">Kolda</a></li>
        		<li><a href="index.php?page=regions/louga/index.html">Louga</a></li>
        		<li><a href="index.php?page=regions/north/index.html">Northern Senegal</a></li>
        		<li><a href="index.php?page=regions/tamba/index.html">Tambacounda</a></li>
        		<li><a href="index.php?page=regions/thies/index.html">Thies</a></li>
            </ul></li>
      	<li><a href="index.php?page=sectors/index.html">Sectors</a>
        	<ul>
        		<li><a href="index.php?page=sectors/agfo/index.html">Agroforestry</a></li>
        		<li><a href="index.php?page=sectors/ecot/index.html">Ecotourism</a></li>
        		<li><a href="index.php?page=sectors/ee/index.html">Environmental Education</a></li>
        		<li><a href="index.php?page=sectors/he/index.html">Health</a>
        			<ul>
        				<li><a href="http://pcsenegal.org/index.php?page=malaria/index.html">PC Senegal & Malaria</a></li>
        				<li><a href="http://pcsenegal.org/index.php?page=malaria/malarious.html">Malarious</a></li>
            		</ul></li>
        		<li><a href="index.php?page=sectors/sed/index.html">Small Ent. Development</a>
        	<ul>
        		<li><a href="index.php?page=sectors/sed/artisan/index.html">Artisan Network</a></li>
            </ul></li>
        		<li><a href="index.php?page=sectors/susag/index.html">Sustainable Rural Agriculture</a></li>
        		<li><a href="index.php?page=sectors/uag/index.html">Urban Agriculture</a></li>
        	</ul></li>
        <li><a href="index.php?page=food_security/index.html">USAID Food Security</a>
        	<ul>
        		<li><a href="index.php?page=food_security/index.html">Overview</a></li>
        		<li><a href="index.php?page=food_security/docs.html">Documents</a></li>
        		<li><a href="index.php?page=food_security/farmers.html">Farmers</a></li>
        		<li><a href="index.php?page=food_security/gardens.html">Gardens</a></li>
        		<li><a href="index.php?page=food_security/markets.html">Markets</a></li>
        		<li><a href="index.php?page=food_security/moringa.html">Moringa</a></li>
        		<li><a href="index.php?page=food_security/nutrition.html">Nutrition</a></li>
        		<li><a href="index.php?page=food_security/papa.html">PAPA</a></li>
        		<li><a href="index.php?page=food_security/permaculture.html">Permaculture</a></li>
        		<li><a href="index.php?page=food_security/projects.html">Projects</a></li>
        		<li><a href="index.php?page=food_security/weekly_update.html">Weekly Update</a></li>
            </ul></li>
        <li><a href="index.php?page=secondary_proj/index.html">Secondary Projects</a>
        	<ul>
        		<li><a href="index.php?page=apptech/index.html">Appropriate Technologies</a>
        			<ul>
        				<li><a href="index.php?page=apptech/briquette_press.html">Briquette Press</a></li>
        				<li><a href="index.php?page=apptech/fruitdrier.html">Fruit Drier</a></li>
        				<li><a href="index.php?page=apptech/stovetec.html">Improved Stoves</a></li>
        				<!--<li><a href="index.php?page=apptech/rope_pump.html">Rope Pump</a></li>
        				<li><a href="index.php?page=apptech/treadle_pump.html">Treadle Pump</a></li>-->
        				<li><a href="index.php?page=apptech/uns.html">Universal Nut Sheller</a></li>
        			</ul></li>
        		<li><a href="index.php?page=gad/index.html">Gender and Development</a>
        			<ul>
        				<li><a href="http://senegad.pcsenegal.org" target="_blank">SeneGAD</a></li>
        				<li><a href="http://ccc.pcsenegal.org" target="_blank"><em>Camp de Connaissance et Croissance</em></a></li>
        			</ul></li>
        		<li><a href="index.php?page=radio/index.html">Radio Production</a>
        			<ul>
        				<li><a href="index.php?page=radio/shows/index.html">Shows</a></li>
        				<li><a href="index.php?page=radio/stations/index.html">Stations</a>
        					<ul>
        						<li><a href="index.php?page=radio/stations/linguere.html">Aida FM (Linguere)</a></li>
        						<li><a href="index.php?page=radio/stations/saraya.html">Giggi Sembe (Kedougou)</a></li>
        						<li><a href="index.php?page=radio/stations/soukouta.html">Radio Niombato (Fatick)</a></li>
        					</ul></li>
        			</ul></li>
      	</ul></li>
        <li><a href="index.php?page=pcresponse/index.html">Peace Corps Response</a></li>
        	<li><a href="http://pcsenegal.org/index.php?page=resources.php&add=tables&tags=case_study">Case Studies</a></li>
      </ul></li>
    <li><a href="index.php?page=about_senegal/index.html">About Senegal</a>
   	<!--<ul>
        <li><a href="index.php?page=about_senegal/history.html">History</a></li>
        <li><a href="index.php?page=about_senegal/culture.html">Culture</a></li>
        <li><a href="index.php?page=about_senegal/cuisine.html">Cuisine</a></li>
        <li><a href="index.php?page=resources/language/language.html">Language</a></li>
      </ul>--></li>
    <li><a href="index.php?page=collaboration/index.html">Collaboration</a>
		<ul>
			<li><a href="index.php?page=collaboration/orgs/against_malaria.html">Against Malaria</a></li>
			<li><a href="index.php?page=collaboration/orgs/app_proj.html">Appropriate Projects</a></li>
			<li><a href="index.php?page=collaboration/orgs/cpi.html">Counterpart International</a></li>
			<li><a href="index.php?page=collaboration/orgs/malaria_no_more.html">Malaria No More</a></li>
			<li><a href="index.php?page=collaboration/orgs/oxfam.html">Oxfam America</a></li>
			<li><a href="index.php?page=collaboration/orgs/right_to_sight.html">Right to Sight and Health</a></li>
			<li><a href="index.php?page=collaboration/orgs/seeds.html">SEEDS</a></li>
			<li><a href="index.php?page=collaboration/orgs/tostan.html">Tostan</a></li>
			<li><a href="index.php?page=collaboration/orgs/tftf.html">Trees for the Future</a></li>
			<li><a href="index.php?page=collaboration/orgs/usaid.html">USAID</a>
            	<ul>
                	<li><a href="index.php?page=food_security/index.html">Food Security Project</a></li>
                </ul></li>
		</ul></li>
    <li><a href="index.php?page=resources/language/index.html">Language</a>
      <ul>
        <li><a href="index.php?page=resources/language/french/index.html">French</a></li>
        <li><a href="index.php?page=resources/language/bassari/index.html">Bassari</a></li>
        <li><a href="index.php?page=resources/language/mandinka/index.html">Mandinka</a></li>
        <li><a href="index.php?page=resources/language/pulaar/index.html">Pulaar</a></li>
        <li><a href="index.php?page=resources/language/sereer/index.html">Sereer</a></li>
        <li><a href="index.php?page=resources/language/wolof/index.html">Wolof</a></li>
      </ul></li>
    <li><a href="http://pcsenegal.org/index.php?page=resources/index.html">Resources</a>
      <ul>
        <li><a href="index.php?page=resources/events/upcoming.php">Upcoming Events</a>
			<ul>
        		<li>upcoming script here</li>
        		</ul></li>
        <li><a href="index.php?page=resources/events/recent.php">Recent Events</a>
        	<ul>
        		<li>Event script here</li>
        	</ul></li>
        <li><a href="http://pcsenegal.org/index.php?page=resources/howto/index.html">How-To Videos & Transcripts</a>
        		<ul>
        			<li><a href="http://pcsenegal.org/index.php?page=resources/howto/beekeeping.html">Beekeeping</a></li>
        			<li><a href="http://pcsenegal.org/index.php?page=resources/howto/gardening.html">Gardening</a></li>
        			<li><a href="http://pcsenegal.org/index.php?page=resources/howto/live_fencing.html">Live Fencing</a></li>
        			<li><a href="http://pcsenegal.org/index.php?page=resources/howto/mango_grafting.html">Mango Grafting</a></li>
        			<li><a href="http://pcsenegal.org/index.php?page=resources/howto/moringa.html">Moringa</a></li>
        			<li><a href="http://pcsenegal.org/index.php?page=resources/howto/seed_storage.html">Seed Storage</a></li>
        		</ul></li>
        <li><a href="index.php?page=radio/index.html">Radio</a>
        		<ul>
        			<li><a href="index.php?page=radio/shows/index.html">Archived Shows</a></li>
        			<li><a href="index.php?page=resources.php&add=tables&tags=radio">Scripts / Transcripts</a></li>
        		</ul></li>
        <li><a href="http://youtube.com/user/pcsenegaladmin/" target="_blank">PC/Senegal Youtube Channel</a></li>
        <li><a href="http://pcsenegal.org/index.php?page=resources.php&add=tables&tags=case_study">Case Studies</a></li>
        <li><a href="http://pcsenegal.org/index.php?page=resources.php&add=tables">Library</a></li>
      </ul></li>
    <li><a href="index.php?page=donate.html">Donate</a></li>
    <li><a href="http://pcv.pcsenegal.org">For Volunteers</a>
        		<ul>
        			<li><a href="index.php?page=pcv/index.html">PCVs</a>
						<ul>
							<li><a href="index.php?page=pcv/funding/index.html">Funding</a></li>
							<li><a href="index.php?page=pcv/calendars/index.html">Calendars</a>
                            	<ul>
									<!--<li><a href="index.php?page=pcv/calendars/ndioum.html">Ndioum</a>
									<li><a href="index.php?page=pcv/calendars/kolda.html">Kolda</a>-->
									<li><a href="index.php?page=pcv/calendars/pape.html">Pape (Tamba / Kedougou)</a>
									<li><a href="index.php?page=pcv/calendars/index.html">PC Senegal</a>
									<!--<li><a href="index.php?page=pcv/calendars/regional.html">Regional</a>
									<li><a href="index.php?page=pcv/calendars/staff_calendar.html">Staff</a>
									<li><a href="index.php?page=pcv/calendars/tamba.html">Tamba</a>-->
									<li><a href="index.php?page=pcv/calendars/training.html">Training</a>
                                </ul></li>
						</ul></li>
        			<li><a href="http://pcvl.pcsenegal.org" target="_blank">PCVLs</a>
                            	<ul>
									<li><a href="http://pcvl.pcsenegal.org/adminer/?server=p50mysql131.secureserver.net" target="_blank">Adminer</a>
                                </ul></li>
        			<!--<li><a href="">RPCVs</a></li>-->
        			<li><a href="http://invitee.pcsenegal.org">Invitees</a></li>
        		</ul></li>
  </ul>  
 
</div>
