<div>
		<iframe align="middle" src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fpcsenegal.org<?php print urlencode('?page='.$_GET['page']); ?>&amp;send=true&amp;layout=standard&amp;width=180&amp;show_faces=true&amp;action=like&amp;colorscheme=light&amp;font=verdana&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:180px; height:80px;" allowTransparency="true">
		</iframe>

<a href="http://twitter.com/hedrickchris" target="_blank"><img src="img/twitter.gif" border="0" /></a>
<a href="http://youtube.com/user/pcsenegaladmin" target="_blank"><img src="img/thumbs/youtube_h25.png" border="0" /></a>
</div>